env:
  ANGULAR_CONFIGURATION: "${{ github.ref_name == 'develop' && 'development' || (github.ref_name == 'homolog' && 'homolog' || 'production' ) }}"

name: Deploy to Firebase Hosting on merge
"on":
  push:
  pull_request:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build --configuration=$ANGULAR_CONFIGURATION
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_IBOOK_FRONTEND }}"
          channelId: live
          projectId: dev-ibook-frontend
